### ISSUE TITLE
case/of lexing expecting something more?

### ISSUE THREAD

**Issue by nlfiedler** [fjl/Sublime-Erlang#31]
I have the following in my code and Sublime-Erlang seems to be expecting something different, as it indicates errors throughout the rest of the source file.

```
    Action = case Event of
        no -> State#state.no;
        yes -> State#state.yes;
        invalid_opt -> fun noop/1
    end,
```

Commenting that block out "fixes" it, as does replacing the comma with a semicolon. I'm filing this simply to make it known. If I can figure out how SublimeText plugins work, I'll dig into this and see if I can fix it.

**Comment by nox** [comment]
Ping? I tried to fix this, to no avail.
